Code Review for [integration-specs] | RoR-Blog App Project
luigirazum/ror-blog pull request #8
Opened 2024-01-30 08:31 UTC by luigirazum

### n+1 fix
#### - Before
  ```bash
  Started GET "/users/5/posts" for 127.0.0.1 at 2024-01-30 01:16:07 -0700
  Processing by PostsController#index as HTML
    Parameters: {"user_id"=>"5"}
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
    ↳ app/controllers/posts_controller.rb:4:in `index'
    Rendering layout layouts/application.html.erb
    Rendering posts/index.html.erb within layouts/application
    Rendered application/_counter.html.erb (Duration: 0.0ms | Allocations: 13)
    Rendered users/_user_hero.html.erb (Duration: 0.3ms | Allocations: 106)
    Post Count (0.4ms)  SELECT COUNT(*) FROM "posts" WHERE "posts"."author_id" = $1  [["author_id", 5]]
    ↳ app/helpers/posts_helper.rb:3:in `render_all_posts'
    Post Load (0.6ms)  SELECT "posts".* FROM "posts" WHERE "posts"."author_id" = $1 ORDER BY "posts"."created_at" DESC  [["author_id", 5]]
    ↳ app/helpers/posts_helper.rb:4:in `render_all_posts'
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Comment Count (3.6ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 16], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Comment Load (0.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2  [["post_id", 16], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:12:in `render_comments'
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 19], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    Rendered collection of comments/_comment.html.erb [1 times] (Duration: 3.2ms | Allocations: 2353)
    Rendered application/_counter.html.erb (Duration: 0.2ms | Allocations: 12)
    Rendered application/_counter.html.erb (Duration: 1.1ms | Allocations: 13)
    Comment Count (1.0ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 15], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Comment Load (0.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2  [["post_id", 15], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:12:in `render_comments'
    User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    Rendered collection of comments/_comment.html.erb [1 times] (Duration: 3.9ms | Allocations: 623)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 13)
    Comment Count (1.1ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 14], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Comment Load (0.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2  [["post_id", 14], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:12:in `render_comments'
    User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 4], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 15], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 13], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    Rendered collection of comments/_comment.html.erb [5 times] (Duration: 14.1ms | Allocations: 2921)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Rendered application/_counter.html.erb (Duration: 0.2ms | Allocations: 13)
    Comment Count (0.6ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 13], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Comment Load (0.7ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2  [["post_id", 13], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:12:in `render_comments'
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 8], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 8], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 13], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    Rendered collection of comments/_comment.html.erb [5 times] (Duration: 9.1ms | Allocations: 2477)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 13)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Comment Count (0.5ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 12], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Rendered application/_empty.html.erb (Duration: 1.0ms | Allocations: 127)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Rendered application/_counter.html.erb (Duration: 0.1ms | Allocations: 12)
    Comment Count (0.5ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2) subquery_for_count  [["post_id", 11], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:11:in `render_comments'
    Comment Load (0.5ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 ORDER BY "comments"."created_at" DESC LIMIT $2  [["post_id", 11], ["LIMIT", 5]]
    ↳ app/helpers/posts_helper.rb:12:in `render_comments'
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 16], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
    ↳ app/views/comments/_comment.html.erb:1
    Rendered collection of comments/_comment.html.erb [3 times] (Duration: 6.2ms | Allocations: 1528)
    Rendered collection of posts/_post.html.erb within posts/_post_comments [6 times] (Duration: 95.4ms | Allocations: 21694)
    Rendered application/_buttons.html.erb (Duration: 0.5ms | Allocations: 280)
    Rendered posts/index.html.erb within layouts/application (Duration: 105 [...]

2024-01-31 16:08 UTC, topeogunleye requested changes
Hi @luigirazum, @porag-m06,  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
- Your code is well-structured and easy to read. You have used descriptive variable names and consistent indentation. 👍
- You have used `let!` to create the user and the posts before each example. This is a good practice to avoid repetition and ensure that the data is available for each test. 👍
- You have used `context` to group your examples by different scenarios. This is a good practice to organize your tests and make them more readable. 👍
- You have used `expect` to assert the expected outcomes of your tests. This is a good practice to write expressive and clear tests. 👍
- You have covered most of the requirements for the user's posts index page. You have tested the user's profile picture, username, number of posts, all posts, and the buttons to view a post and add a new comment. You have also tested the post's title, body, and recent comments. 👍
- You have used `page.all` to iterate over the posts on the user's posts index page. This is a good practice to test multiple elements with the same selector. 👍
- You have used `within` to scope your assertions to a specific element. This is a good practice to avoid ambiguity and make your tests more robust. 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-31 16:08 UTC, topeogunleye commented on spec/system/users/show_spec.rb
> +
Hello, 😊

I have reviewed your code and here are some comments:

- Your code is well-structured and easy to read. You have used descriptive variable names and consistent indentation. 👍
- You have used `let!` to create the user and the posts before each example. This is a good practice to avoid repetition and ensure that the data is available for each test. 👍
- You have used `context` to group your examples by different scenarios. This is a good practice to organize your tests and make them more readable. 👍
- You have used `expect` to assert the expected outcomes of your tests. This is a good practice to write expressive and clear tests. 👍
- You have covered most of the requirements for the user show page. You have tested the user's profile picture, username, number of posts, bio, first 3 posts, and the buttons to view all posts and add a new comment. You have also tested the post's title, body, and counters. 👍
- You have used `page.all` to iterate over the posts on the user show page. This is a good practice to test multiple elements with the same selector. 👍
- You have used `within` to scope your assertions to a specific element. This is a good practice to avoid ambiguity and make your tests more robust. 👍

However, there is one requirement that you have missed:

- You have not tested that the user is redirected to the post's show page when they click on a user's post. This is an important functionality that should be verified by your tests. You can use `click_on` to simulate the user's action and `current_path` to check the current URL. You can learn more about these methods [here].

Here is an example of how you can test this requirement:

```ruby
it "> redirects to the post's show page when clicking on a post's title" do
  page.all('.post').each_with_index do |post, i|
    within(post) do
      click_on "Post ##{user_posts.reverse[i].id} | #{user_posts.reverse[i].title}"
      expect(current_path).to eq(user_post_path(user, user_posts.reverse[i]))
      go_back
    end
  end
end
```

I hope you find these comments helpful. If you have any questions or feedback, please let me know. 😊

2024-01-31 16:08 UTC, topeogunleye commented on spec/system/posts/index_spec.rb
> +
Hello,😊

I have reviewed your code and here are some comments:

- Your code is well-structured and easy to read. You have used descriptive variable names and consistent indentation. 👍
- You have used `let!` to create the user and the posts before each example. This is a good practice to avoid repetition and ensure that the data is available for each test. 👍
- You have used `context` to group your examples by different scenarios. This is a good practice to organize your tests and make them more readable. 👍
- You have used `expect` to assert the expected outcomes of your tests. This is a good practice to write expressive and clear tests. 👍
- You have covered most of the requirements for the user's posts index page. You have tested the user's profile picture, username, number of posts, all posts, and the buttons to view a post and add a new comment. You have also tested the post's title, body, and recent comments. 👍
- You have used `page.all` to iterate over the posts on the user's posts index page. This is a good practice to test multiple elements with the same selector. 👍
- You have used `within` to scope your assertions to a specific element. This is a good practice to avoid ambiguity and make your tests more robust. 👍

However, there is one requirement that you have missed:

- You have not tested that the user can see a section for pagination if there are more posts than fit on the view. This is an important functionality that should be verified by your tests. You can use `have_selector` to check if the pagination element is present on the page. You can learn more about this method [[here](https://stackoverflow.com/questions/55311731/rspec-for-pagination)](^1^).

Here is an example of how you can test this requirement:

```ruby
context "- can see pagination section" do
  it "> shows pagination if there are more posts than per page limit" do
    create_list(:post, PER_PAGE + 1, user: user) # create more posts than the per page limit
    visit user_posts_path(user)
    expect(page).to have_selector(".pagination") # check if the pagination element is present
  end

  it "> does not show pagination if there are less posts than per page limit" do
    create_list(:post, PER_PAGE - 1, user: user) # create less posts than the per page limit
    visit user_posts_path(user)
    expect(page).not_to have_selector(".pagination") # check if the pagination element is absent
  end
end
```

I hope you find these comments helpful. If you have any questions or feedback, please let me know. 😊

Source: Conversation with Bing, 1/31/2024
(1) ruby on rails 5 - Rspec for pagination - Stack Overflow. https://stackoverflow.com/questions/55311731/rspec-for-pagination.
(2) ruby - RSpec test for pagination - Code Review Stack Exchange. https://codereview.stackexchange.com/questions/77180/rspec-test-for-pagination.
(3) Testing will paginate gem with Rspec/Capybara - Stack Overflow. https://stackoverflow.com/questions/43099347/testing-will-paginate-gem-with-rspec-capybara.

2024-01-31 17:51 UTC, luigirazum commented on spec/system/posts/index_spec.rb
> +
Thanks @topeogunleye, just one question.
What if I don't use the pagination?
I mean, the page scrolls showing the recent posts and all the posts.

2024-01-31 17:53 UTC, topeogunleye commented on spec/system/posts/index_spec.rb
> +
@luigirazum. Given it is a requirement to test for pagination. I suggest that you add pagination to your page.

2024-02-01 12:41 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi Team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-01 14:58 UTC, merged